### ISSUE TITLE
Creating task when no project exists crashes

### ISSUE THREAD

**Issue by saward** [ajaxray/geek-life#1]
Just tried this out, and when I tried creating a new task without first creating a project, it crashes.  Presumably because projectPane.activeProject is nil?

**Comment by ajaxray** [comment]
Thanks for reporting. 👍 
Fixing it soon - should be resolved by next release.

**Comment by ajaxray** [comment]
Hello @saward ,
The issue is fixed. Now, even the "New Task" input will not be visible without active project.
Can you please check and confirm?
