### ISSUE TITLE
Add SHA256 of released binary

### ISSUE THREAD

**Issue by Zeuh** [ajaxray/geek-life#14]
SHA256 of released binary is needed for auto-update automation to control that downloaded binary is ok.

**Comment by ajaxray** [comment]
@Zeuh,  
Thanks for the suggestion.

Made it [part of build](https://github.com/ajaxray/geek-life/commit/0208277ce1b05da06823d3391e280383456149e3) and started adding in release note from [release v0.1.2](https://github.com/ajaxray/geek-life/releases/tag/v0.1.2).
