### ISSUE TITLE
New dynamic list "Unscheduled" - all tasks without a due date

### ISSUE THREAD

**Issue by jemx** [ajaxray/geek-life#18]
Hi,

I think it would be cool to have an overview of all tasks across all projects, without depending on time. I have some tasks that don't have a due date and are therefore not shown in the dynamic lists.

**Comment by ajaxray** [comment]
Hello @jemx,
Thanks for pointing this out. 👍🏼 

So, a new dynamic list - "Unscheduled" will help to list them all in same page.
I am modifying the issue title to propose it as a feature. 
Hope we'll include it soon in a new release.
