### ISSUE TITLE
Browsing lists and panels using vim navigation keys

### ISSUE THREAD

**Issue by ajaxray** [ajaxray/geek-life#2]
Browsing lists and panels using vim navigation keys will be much natural for vim users.

- Navigating lists with `j` and `k`
- Moving to panel (projects, tasks, task-detail) with `h` and `l`

Based on a feedback on [Reddit](https://www.reddit.com/r/golang/comments/h8f6jl/geeklife_a_full_featured_cli_task_todo_list/fus1io6/)

**Comment by mwat56** [comment]
One could also wish for the old `WordStar` diamond to navigate.
But …
I think it would be a better option to allow to use an external editor (via INI-file or commandline option). That way everybody could use their preferred editing environment.

**Comment by ajaxray** [comment]
@mwat56 Thanks for your recommendation.

Implementing external editor is in progress. It will open Task Detail in whatever editor is set in `$EDITOR` env variable, vim by default.
See #6

**Comment by ajaxray** [comment]
A little to initial plan - not gong to implement moving to right panel with `l`.
Because right side content depends on selection of left panel. So moving towards the right side panel should be based on selecting item with `Enter`.

Here is the plan I am going to implement now.
```
+------+----------------------+-----------------------+
|  P   |         T            |         D             |
|      |                      |                       |
|    Entr=>    ↓   ↑        Entr=>                    |
|      |      tab TAB         |                       |
|   <=Esc/h    j   k       <=Esc/h                    |
|      |                      |                       |
+------+----------------------+-----------------------+
```

So, what it's trying to visualize is -
- Selecting an item with `Enter` will move you to right panel. That means - 
    - Selecting a Project will load it's tasks and move to Tasks panel
    - Selecting a Task will load task detail and move to Detail panel
- Use `Esc` or `h` (like vim) to move to left panel. Details to Tasks to Projects.
- To navigate a list (Project list or Task list), 
    - Use `↓` or `j` or `Tab` to go down
    - Use `↑` or `k` or `Shift+Tab` to go up
