### ISSUE TITLE
Delete task/project confirmation

### ISSUE THREAD

**Issue by Bezifabr** [ajaxray/geek-life#28]
IMO deleting tasks/projects without double confirmation can lead to accidentally removed lists.

Please implement a dialog asking if the user really wants to delete stuff.

example:
1. User press a button to delete a project
2. Terminal displays a dialog:

-------------------------------------
| Do you want to delete the project? |
|                                                             |
|           Yes                            No           |
-------------------------------------

If user press 'yes' then it's deleted
If user press 'no' then nothing happens

**Comment by Robert-M-Muench** [comment]
Yes, just hit D accidentally... no fun... really not.
