### ISSUE TITLE
Problem in displaying the horizontal line.

### ISSUE THREAD

**Issue by saaremaa** [ajaxray/geek-life#34]
Hi.
In Windows 10, I have a problem in displaying the horizontal line in projects and detailed information on the task. 
![2021-11-26_11-31-54](https://user-images.githubusercontent.com/2886680/143720950-4f594d2e-ae68-461d-a4cc-4ac3f909b5f3.png)
Is there such a problem in other operating systems?
For me this problem is solved by changing the rune tcell.RuneS3 to tcell.RuneHLine in the code.
![2021-11-27_22-19-50](https://user-images.githubusercontent.com/2886680/143721160-4b5be500-9976-4cf4-9f23-3bbb120cc83f.png)

If necessary, I can provide PR.

**Comment by ajaxray** [comment]
Dear @saaremaa ,

Yes, I have checked `tcell.RuneHLine` for mac terminal and iTerm too - working perfectly. 👍🏼

Sure, a PR is much appreciated. 😊

**Comment by saaremaa** [comment]
https://github.com/ajaxray/geek-life/pull/36#issue-1071515305

**Comment by ajaxray** [comment]
Solved in #36 
Thanks to @saaremaa ❤️
