### ISSUE TITLE
High Priority Feature

### ISSUE THREAD

**Issue by WacoHolve** [ajaxray/geek-life#43]
Hi, I just started using this and I really enjoy it so far, one thing that I think would be nice is a way to be able to identify tasks as high priority. Currently I can set them to due today, but would be great if there was another setting where it'd draw even more awareness to them.

**Comment by ajaxray** [comment]
Hello @WacoHolve,

Thanks a lot for your interest.
We'll soon try to add your feature request.

However, if you have already added it on a different fork, a PR is very much welcome. 😄
