### ISSUE TITLE
Date setting error

### ISSUE THREAD

**Issue by tuanpham96** [ajaxray/geek-life#7]
Hi, I'm having trouble with setting the date, whatever I enter, it sets back to a day before.
![geek-life_date-setting-error](https://user-images.githubusercontent.com/42875763/84944041-d30d1400-b0aa-11ea-8285-4daf037ff412.gif)

**Comment by ajaxray** [comment]
Hello @tuanpham96 ,

Thanks a lot for reporting 👍 
But, I have tried but could not reproduce this issue.

Can you please tell me about your OS and timezone and system time?

**Comment by tuanpham96** [comment]
It’s ubuntu 18.04, CST

**Comment by chuyuanchen** [comment]
Same here, with Ubuntu 18.04. Besides, the "+1" button doesn't do anything while "-1" button minus two days instead of one.

**Comment by ajaxray** [comment]
Hello @tuanpham96 and @chuyuanchen,

Thanks for reporting.

I have started an ubuntu 18.04 from docker to test the issue. And got the following result.
- Setting date manually - https://share.getcloudapp.com/5zuXN7ny
- Setting date using buttons - https://share.getcloudapp.com/ApuA98qA

But still, I'll try to dig down more to solve the issue you've found. 
Can you please tell me a few more points? 
- What is your timezone? Is your system set to local time or UTC?
- Did you build the app from source or downloaded from release?
- If Downloaded from release, 
    - Can you please try building from source if possible?
    - I have uploaded newer version of binaries at Jun 16 8PM in the current latest release . Can you please download it and try again?

Again, thanks for helping me in making it bug free 👍
